version: "3.5"
services:
  postgres:
   volumes: 
      - postgres_api_data:/data/postgres
  swiggy-ms:
   container_name: swiggy_ms
   command: npm run start:debug
   environment:
     NPM_INSTALL: ENABLE
     TYPEORM_MIGRATION: ENABLE
   ports:
     - 4000:3000
     - 5858:5858
   volumes:
     - ./swiggy-ms:/app

volumes:
  postgres_api_data: {}
  swiggy_modules: {}
