version: "3.5"
services:
  nginx:
    image: nginx:1.11
    ports:
      - 88:80
      - 443:443
    depends_on:
      - gatekeeper-ms
      - swiggy-ui-ms
    networks:
      - swiggy-network
  swiggy-ui-ms:
    build: ./swiggy-ui-ms/
    image: swiggy-ui-ms
    container_name: swiggy-ui-ms
    environment:
      - NODE_ENV=local
    depends_on:
      - gatekeeper-ms
    ports:
      - 5000:3000
    networks:
      - swiggy-network
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: swiggy_apis
      POSTGRES_USER: swiggy
      POSTGRES_PASSWORD: swiggy
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - swiggy-network
  gatekeeper-ms:
    container_name: gatekeeper-ms
    build: ./gatekeeper-ms/
    image: gatekeeper-ms
    ports:
      - 4001:3000
    depends_on:
      - postgres
    networks:
      - swiggy-network
  swiggy-ms:
    build: ./swiggy-ms/
    image: swiggy-ms
    container_name: swiggy_ms
    environment:
      - NODE_ENV=local
    ports:
      - 4007:3000
      - 8209:8202
    depends_on:
      - postgres
    networks:
      - swiggy-network
  gateway-ms:
    build: ./gateway-ms/
    image: gateway-ms
    container_name: gateway-ms
    environment:
      - NODE_ENV=local
    ports:
      - 4007:3000
      - 8209:8202
    depends_on:
      - postgres
    networks:
      - swiggy-network      
networks:
  swiggy-network:
    driver: bridge
    name: swiggy-network
