version: "3.5"
services:
  postgres:
    image: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres_api_data:/data/postgres
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    networks:
      - swiggy-network
  swiggy-ms:
    build: ./swiggy-ms/
    image: swiggy-ms
    container_name: swiggy_ms
    environment:
      - NODE_ENV=local
    depends_on:
      - postgres
    networks:
      - swiggy-network     
networks:
  swiggy-network:
    driver: bridge
    name: swiggy-network
